### ISSUE TITLE
How do I run the code on my Jetson nano

### ISSUE THREAD

**Issue by agasheaditya** [VisualComputingInstitute/2D_lidar_person_detection#3] opened 2021-02-05 09:10 UTC
Hey folks,
Can you please guide me on this. I want to run this code on my Jetson Nano. I have ROS Melodic installed. Can you please briefly explain me that how to run the project. Since I am newbie to ROS. 
Your help will be great for me. Thanks in advance.

**Comment by Pandoro** [comment] 2021-02-05 09:31
Hey Aditya,

the README specifies exactly how to start install and run the project. Please follow the specified steps. If there are basic things about ROS that you don't understand, there are tons of tutorials out there to explain them.

I'm closing this as the question is already answered in the README. If you encounter specific issues while running the code, you can re-open this, but make sure to describe in detail what is going wrong. Otherwise it is very difficult to help you.

**Closed by Pandoro** 2021-02-05 09:31 UTC

**Comment by agasheaditya** [comment] 2021-02-05 09:59
> Hey Aditya,
> 
> the README specifies exactly how to start install and run the project. Please follow the specified steps. If there are basic things about ROS that you don't understand, there are tons of tutorials out there to explain them.
> 
> I'm closing this as the question is already answered in the README. If you encounter specific issues while running the code, you can re-open this, but make sure to describe in detail what is going wrong. Otherwise it is very difficult to help you.

```
root@devise-jetson:/home/devise/test_codes/catkin_ws# roslaunch dr_spaam_ros dr_spaam_ros.launch 
... logging to /root/.ros/log/4cefe58c-6798-11eb-b8e3-00044bec2f6b/roslaunch-devise-jetson-20419.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://devise-jetson:41945/

SUMMARY
========

PARAMETERS
 * /dr_spaam_ros/conf_thresh: 0.5
 * /dr_spaam_ros/detector_model: DROW3
 * /dr_spaam_ros/panoramic_scan: True
 * /dr_spaam_ros/publisher/detections/latch: False
 * /dr_spaam_ros/publisher/detections/queue_size: 1
 * /dr_spaam_ros/publisher/detections/topic: /dr_spaam_detections
 * /dr_spaam_ros/publisher/rviz/latch: False
 * /dr_spaam_ros/publisher/rviz/queue_size: 1
 * /dr_spaam_ros/publisher/rviz/topic: /dr_spaam_rviz
 * /dr_spaam_ros/stride: 1
 * /dr_spaam_ros/subscriber/scan/queue_size: 1
 * /dr_spaam_ros/subscriber/scan/topic: /segway/scan_multi
 * /dr_spaam_ros/weight_file: /home/jia/ckpts/c...
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    dr_spaam_ros (dr_spaam_ros/node.py)

ROS_MASTER_URI=http://localhost:11311

process[dr_spaam_ros-1]: started with pid [20436]
Traceback (most recent call last):
  File "/home/devise/test_codes/catkin_ws/src/2D_lidar_person_detection/dr_spaam_ros/scripts/node.py", line 4, in <module>
    from dr_spaam_ros.dr_spaam_ros import DrSpaamROS
  File "/home/devise/test_codes/catkin_ws/src/2D_lidar_person_detection/dr_spaam_ros/src/dr_spaam_ros/dr_spaam_ros.py", line 9, in <module>
    from dr_spaam.detector import Detector
ImportError: No module named dr_spaam.detector
[dr_spaam_ros-1] process has died [pid 20436, exit code 1, cmd /home/devise/test_codes/catkin_ws/src/2D_lidar_person_detection/dr_spaam_ros/scripts/node.py __name:=dr_spaam_ros __log:=/root/.ros/log/4cefe58c-6798-11eb-b8e3-00044bec2f6b/dr_spaam_ros-1.log].
log file: /root/.ros/log/4cefe58c-6798-11eb-b8e3-00044bec2f6b/dr_spaam_ros-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
root@devise-jetson:/home/devise/test_codes/catkin_ws# 

```

I am getting this error when I followed the instruction set. Thanks

**Comment by Pandoro** [comment] 2021-02-05 11:35
Looking at the error the Detector module cannot be found. Are you sure you installed the package after cloning the repo:
```
git clone https://github.com/VisualComputingInstitute/2D_lidar_person_detection.git
cd dr_spaam
python setup.py install
```

If you did and it is globally installed/in a virtuel/conda environment you should be able to run python and then import the Detector using ``from dr_spaam.detector import Detector``. Make sure this works before running the node.

**Comment by agasheaditya** [comment] 2021-02-05 12:27
```
root@devise-jetson:/home/devise/catkin_ws# roslaunch dr_spaam_ros dr_spaam_ros.launch
... logging to /root/.ros/log/10c25e34-67aa-11eb-8983-00044bec2f6b/roslaunch-devise-jetson-13390.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://devise-jetson:45517/

SUMMARY
========

PARAMETERS
 * /dr_spaam_ros/conf_thresh: 0.5
 * /dr_spaam_ros/detector_model: DROW3
 * /dr_spaam_ros/panoramic_scan: True
 * /dr_spaam_ros/publisher/detections/latch: False
 * /dr_spaam_ros/publisher/detections/queue_size: 1
 * /dr_spaam_ros/publisher/detections/topic: /dr_spaam_detections
 * /dr_spaam_ros/publisher/rviz/latch: False
 * /dr_spaam_ros/publisher/rviz/queue_size: 1
 * /dr_spaam_ros/publisher/rviz/topic: /dr_spaam_rviz
 * /dr_spaam_ros/stride: 1
 * /dr_spaam_ros/subscriber/scan/queue_size: 1
 * /dr_spaam_ros/subscriber/scan/topic: /segway/scan_multi
 * /dr_spaam_ros/weight_file: /home/devise/Down...
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    dr_spaam_ros (dr_spaam_ros/node.py)

ROS_MASTER_URI=http://localhost:11311

process[dr_spaam_ros-1]: started with pid [13406]
Traceback (most recent call last):
  File "/home/devise/catkin_ws/src/2D_lidar_person_detection/src/dr_spaam_ros/scripts/node.py", line 4, in <module>
    from dr_spaam_ros.dr_spaam_ros import DrSpaamROS
  File "/home/devise/catkin_ws/src/2D_lidar_person_detection/src/dr_spaam_ros/src/dr_spaam_ros/dr_spaam_ros.py", line 9, in <module>
    from dr_spaam.detector import Detector
ImportError: No module named dr_spaam.detector
[dr_spaam_ros-1] process has died [pid 13406, exit code 1, cmd /home/devise/catkin_ws/src/2D_lidar_person_detection/src/dr_spaam_ros/scripts/node.py __name:=dr_spaam_ros __log:=/root/.ros/log/10c25e34-67aa-11eb-8983-00044bec2f6b/dr_spaam_ros-1.log].
log file: /root/.ros/log/10c25e34-67aa-11eb-8983-00044bec2f6b/dr_spaam_ros-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
root@devise-jetson:/home/devise/catkin_ws# python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dr_spaam_ros.dr_spaam_ros import DrSpaamROS
>>> from dr_spaam.detector import Detector
>>> 

```

Hello @Pandoro ,
I have installed the package globally, then also it is giving me error like this. 
Can you please elaborate briefly  that how should I run the code.
 Thanks.

**Comment by Pandoro** [comment] 2021-02-05 12:38
I'm wondering if this is still a python issue and roslaunch stats python 2.7. This depends on which version of ROS you are using.
Also have a look at issue #1 

If this is the problem indeed, it should work if create a python 3 virtual environment or maybe by changing your pythonpath to use python3 instead.

**Comment by agasheaditya** [comment] 2021-02-05 12:55
Thanks for your prompt reply @Pandoro, I tried every possible thing with python 3.  can we please connect on google meets so that we can have a look at it and get your proper installation of package guidance?
Thank you .

**Comment by danjia21** [comment] 2021-02-05 13:02
@agasheaditya The default python interpreter on Jetson Nano is probably python2 (you can check by `python --version`), and that interpreter is invoked by roslaunch. You should instead create a virtual environment with python3, install `dr_spaam` to that environment, then call roslaunch from that environment (checkout the issue #1 referred by @Pandoro).

If you are not familiar with how virtual environment works for python, I suggest reading many of the tutorials online.

**Comment by agasheaditya** [comment] 2021-02-05 13:05
Okay.thank you. I'll try this too. If something required I'll get back to you. Thanks for being prompt and helpful 😊

**Comment by agasheaditya** [comment] 2021-02-13 05:46
hello @Pandoro @danjia21, I tried the way you suggested like using python3 environment to build and launch the node. but it didn't worked. So, I did installation of ROS again and still I am getting the same error. 
I can give you the build logs if you want to see it. But can you also guide me again for building the same project. 
Thank you 
[build.cmake.000.log](https://github.com/VisualComputingInstitute/2D_lidar_person_detection/files/5975218/build.cmake.000.log)
[build.loadenv.001.log](https://github.com/VisualComputingInstitute/2D_lidar_person_detection/files/5975219/build.loadenv.001.log)
[build.symlink.000.log](https://github.com/VisualComputingInstitute/2D_lidar_person_detection/files/5975220/build.symlink.000.log)
[build.symlink.001.log](https://github.com/VisualComputingInstitute/2D_lidar_person_detection/files/5975221/build.symlink.001.log)

**Comment by Pandoro** [comment] 2021-02-13 10:48
As far as I can tell, launching from within a virtual environment is the
only practical way of getting it to work. From "it didn't work" it's hard
to tell what the problem is. Re-installing ROS will not make a difference
and the build logs are not very interesting, given that nothing really
needs to be built, files just need to be installed. I have never looked at
such logs, but I don't see any errors, so that part should be fine.

**Comment by danjia21** [comment] 2021-02-13 19:56
@agasheaditya you are doing `sudo python3 setup.py install` to install `dr_spaam`. The `roslaunch` however will invoke python (not python3). I suspect in your setup these two interpreters are not the same. That's why `dr_spaam` could not be found by `roslaunch`.

**Comment by agasheaditya** [comment] 2021-02-14 02:36
@Pandoro @danjia21 okay. I'll check once again. 
Thank you.
